version: '3.1'

services:

  postgresql:
    image: postgres
    container_name: pg_container
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - mydata:/home/db/data/postgres
      - ./sql-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: products

volumes:
  mydata: {}