create table if not exists public.product
(
    id          integer generated by default as identity
    primary key,
    title       varchar(200)     not null,
    description varchar(200)     not null,
    price       double precision not null,
    stock       integer          not null,
    condition   varchar(100),
    user_id     integer,
    img         varchar(500)
    );

alter table public.product
    owner to root;


